/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppTest {
        "match": MatchResults;
    }
    interface ComopoentGiteeMenu {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTestElement extends Components.AppTest, HTMLStencilElement {
    }
    var HTMLAppTestElement: {
        prototype: HTMLAppTestElement;
        new (): HTMLAppTestElement;
    };
    interface HTMLComopoentGiteeMenuElement extends Components.ComopoentGiteeMenu, HTMLStencilElement {
    }
    var HTMLComopoentGiteeMenuElement: {
        prototype: HTMLComopoentGiteeMenuElement;
        new (): HTMLComopoentGiteeMenuElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-test": HTMLAppTestElement;
        "comopoent-gitee-menu": HTMLComopoentGiteeMenuElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppTest {
        "match"?: MatchResults;
    }
    interface ComopoentGiteeMenu {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-test": AppTest;
        "comopoent-gitee-menu": ComopoentGiteeMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-test": LocalJSX.AppTest & JSXBase.HTMLAttributes<HTMLAppTestElement>;
            "comopoent-gitee-menu": LocalJSX.ComopoentGiteeMenu & JSXBase.HTMLAttributes<HTMLComopoentGiteeMenuElement>;
        }
    }
}
