/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RtTest {
    }
}
declare global {
    interface HTMLRtTestElement extends Components.RtTest, HTMLStencilElement {
    }
    var HTMLRtTestElement: {
        prototype: HTMLRtTestElement;
        new (): HTMLRtTestElement;
    };
    interface HTMLElementTagNameMap {
        "rt-test": HTMLRtTestElement;
    }
}
declare namespace LocalJSX {
    interface RtTest {
    }
    interface IntrinsicElements {
        "rt-test": RtTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rt-test": LocalJSX.RtTest & JSXBase.HTMLAttributes<HTMLRtTestElement>;
        }
    }
}
