/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
        /**
          * 是否可点击
         */
        "dsDanger": boolean;
        /**
          * 是否可点击
         */
        "dsDisabled": boolean;
        /**
          * 设置载入状态
         */
        "dsLoadding": boolean;
        /**
          * 根据类型显示按钮的样式
         */
        "dsType": 'default' | 'primary' | 'dashed' | 'link' | 'text';
    }
    interface DsDivider {
        /**
          * 是否虚线
         */
        "dsDashed": boolean;
        /**
          * 文本位置
         */
        "dsTextDirection": 'center' | 'left' | 'right';
        /**
          * 分割线的类型,水平还是垂直
         */
        "dsType": 'horizontal' | 'vertical';
    }
    interface DsSpace {
    }
    interface DsTypography {
        /**
          * 主元素显示的HTml
         */
        "dsTag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'p' | 'span';
        /**
          * 文本类型
         */
        "dsType": 'default' | 'secondary' | 'warning'
    | 'danger' | 'success' | 'disabled';
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsDividerElement extends Components.DsDivider, HTMLStencilElement {
    }
    var HTMLDsDividerElement: {
        prototype: HTMLDsDividerElement;
        new (): HTMLDsDividerElement;
    };
    interface HTMLDsSpaceElement extends Components.DsSpace, HTMLStencilElement {
    }
    var HTMLDsSpaceElement: {
        prototype: HTMLDsSpaceElement;
        new (): HTMLDsSpaceElement;
    };
    interface HTMLDsTypographyElement extends Components.DsTypography, HTMLStencilElement {
    }
    var HTMLDsTypographyElement: {
        prototype: HTMLDsTypographyElement;
        new (): HTMLDsTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-divider": HTMLDsDividerElement;
        "ds-space": HTMLDsSpaceElement;
        "ds-typography": HTMLDsTypographyElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        /**
          * 是否可点击
         */
        "dsDanger"?: boolean;
        /**
          * 是否可点击
         */
        "dsDisabled"?: boolean;
        /**
          * 设置载入状态
         */
        "dsLoadding"?: boolean;
        /**
          * 根据类型显示按钮的样式
         */
        "dsType"?: 'default' | 'primary' | 'dashed' | 'link' | 'text';
    }
    interface DsDivider {
        /**
          * 是否虚线
         */
        "dsDashed"?: boolean;
        /**
          * 文本位置
         */
        "dsTextDirection"?: 'center' | 'left' | 'right';
        /**
          * 分割线的类型,水平还是垂直
         */
        "dsType"?: 'horizontal' | 'vertical';
    }
    interface DsSpace {
    }
    interface DsTypography {
        /**
          * 主元素显示的HTml
         */
        "dsTag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'p' | 'span';
        /**
          * 文本类型
         */
        "dsType"?: 'default' | 'secondary' | 'warning'
    | 'danger' | 'success' | 'disabled';
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-divider": DsDivider;
        "ds-space": DsSpace;
        "ds-typography": DsTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-divider": LocalJSX.DsDivider & JSXBase.HTMLAttributes<HTMLDsDividerElement>;
            "ds-space": LocalJSX.DsSpace & JSXBase.HTMLAttributes<HTMLDsSpaceElement>;
            "ds-typography": LocalJSX.DsTypography & JSXBase.HTMLAttributes<HTMLDsTypographyElement>;
        }
    }
}
