/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
        /**
          * 是否可点击
         */
        "dsDanger": boolean;
        /**
          * 是否可点击
         */
        "dsDisabled": boolean;
        /**
          * 设置载入状态
         */
        "dsLoadding": boolean;
        /**
          * 根据类型显示按钮的样式
         */
        "dsType": 'default' | 'primary' | 'dashed' | 'link' | 'text';
    }
    interface DsTypography {
        /**
          * 主元素显示的HTml
         */
        "dsTag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'p' | 'span';
        /**
          * 文本类型
         */
        "dsType": 'default' | 'secondary' | 'warning' | 'danger' | 'success';
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsTypographyElement extends Components.DsTypography, HTMLStencilElement {
    }
    var HTMLDsTypographyElement: {
        prototype: HTMLDsTypographyElement;
        new (): HTMLDsTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-typography": HTMLDsTypographyElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        /**
          * 是否可点击
         */
        "dsDanger"?: boolean;
        /**
          * 是否可点击
         */
        "dsDisabled"?: boolean;
        /**
          * 设置载入状态
         */
        "dsLoadding"?: boolean;
        /**
          * 根据类型显示按钮的样式
         */
        "dsType"?: 'default' | 'primary' | 'dashed' | 'link' | 'text';
    }
    interface DsTypography {
        /**
          * 主元素显示的HTml
         */
        "dsTag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'p' | 'span';
        /**
          * 文本类型
         */
        "dsType"?: 'default' | 'secondary' | 'warning' | 'danger' | 'success';
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-typography": DsTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-typography": LocalJSX.DsTypography & JSXBase.HTMLAttributes<HTMLDsTypographyElement>;
        }
    }
}
