/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
        /**
          * 根据类型显示按钮的样式
         */
        "dsType": 'default' | 'primary' | 'dashed' | 'link' | 'text';
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        /**
          * 根据类型显示按钮的样式
         */
        "dsType"?: 'default' | 'primary' | 'dashed' | 'link' | 'text';
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
        }
    }
}
