/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Dsb5FunctionTest {
    }
    interface Dsb5Test {
        /**
          * 一个字符串参数
         */
        "prop": string;
        /**
          * 一个字符串数组参数1
         */
        "propArr": string[];
    }
}
declare global {
    interface HTMLDsb5FunctionTestElement extends Components.Dsb5FunctionTest, HTMLStencilElement {
    }
    var HTMLDsb5FunctionTestElement: {
        prototype: HTMLDsb5FunctionTestElement;
        new (): HTMLDsb5FunctionTestElement;
    };
    interface HTMLDsb5TestElement extends Components.Dsb5Test, HTMLStencilElement {
    }
    var HTMLDsb5TestElement: {
        prototype: HTMLDsb5TestElement;
        new (): HTMLDsb5TestElement;
    };
    interface HTMLElementTagNameMap {
        "dsb5-function-test": HTMLDsb5FunctionTestElement;
        "dsb5-test": HTMLDsb5TestElement;
    }
}
declare namespace LocalJSX {
    interface Dsb5FunctionTest {
    }
    interface Dsb5Test {
        /**
          * 一个字符串参数
         */
        "prop"?: string;
        /**
          * 一个字符串数组参数1
         */
        "propArr"?: string[];
    }
    interface IntrinsicElements {
        "dsb5-function-test": Dsb5FunctionTest;
        "dsb5-test": Dsb5Test;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dsb5-function-test": LocalJSX.Dsb5FunctionTest & JSXBase.HTMLAttributes<HTMLDsb5FunctionTestElement>;
            "dsb5-test": LocalJSX.Dsb5Test & JSXBase.HTMLAttributes<HTMLDsb5TestElement>;
        }
    }
}
