/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Ant2designHome {
    }
    interface Antdesign2Preview {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface CodeShow {
    }
}
declare global {
    interface HTMLAnt2designHomeElement extends Components.Ant2designHome, HTMLStencilElement {
    }
    var HTMLAnt2designHomeElement: {
        prototype: HTMLAnt2designHomeElement;
        new (): HTMLAnt2designHomeElement;
    };
    interface HTMLAntdesign2PreviewElement extends Components.Antdesign2Preview, HTMLStencilElement {
    }
    var HTMLAntdesign2PreviewElement: {
        prototype: HTMLAntdesign2PreviewElement;
        new (): HTMLAntdesign2PreviewElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCodeShowElement extends Components.CodeShow, HTMLStencilElement {
    }
    var HTMLCodeShowElement: {
        prototype: HTMLCodeShowElement;
        new (): HTMLCodeShowElement;
    };
    interface HTMLElementTagNameMap {
        "ant2design-home": HTMLAnt2designHomeElement;
        "antdesign2-preview": HTMLAntdesign2PreviewElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "code-show": HTMLCodeShowElement;
    }
}
declare namespace LocalJSX {
    interface Ant2designHome {
    }
    interface Antdesign2Preview {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface CodeShow {
        "onExpendChange"?: (event: CustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "ant2design-home": Ant2designHome;
        "antdesign2-preview": Antdesign2Preview;
        "app-home": AppHome;
        "app-root": AppRoot;
        "code-show": CodeShow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ant2design-home": LocalJSX.Ant2designHome & JSXBase.HTMLAttributes<HTMLAnt2designHomeElement>;
            "antdesign2-preview": LocalJSX.Antdesign2Preview & JSXBase.HTMLAttributes<HTMLAntdesign2PreviewElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "code-show": LocalJSX.CodeShow & JSXBase.HTMLAttributes<HTMLCodeShowElement>;
        }
    }
}
