/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsForm1 {
    }
    interface DsInput1 {
        "dsValue": any;
    }
    interface DsSelect1 {
        "dsValue": any;
    }
}
declare global {
    interface HTMLDsForm1Element extends Components.DsForm1, HTMLStencilElement {
    }
    var HTMLDsForm1Element: {
        prototype: HTMLDsForm1Element;
        new (): HTMLDsForm1Element;
    };
    interface HTMLDsInput1Element extends Components.DsInput1, HTMLStencilElement {
    }
    var HTMLDsInput1Element: {
        prototype: HTMLDsInput1Element;
        new (): HTMLDsInput1Element;
    };
    interface HTMLDsSelect1Element extends Components.DsSelect1, HTMLStencilElement {
    }
    var HTMLDsSelect1Element: {
        prototype: HTMLDsSelect1Element;
        new (): HTMLDsSelect1Element;
    };
    interface HTMLElementTagNameMap {
        "ds-form-1": HTMLDsForm1Element;
        "ds-input-1": HTMLDsInput1Element;
        "ds-select-1": HTMLDsSelect1Element;
    }
}
declare namespace LocalJSX {
    interface DsForm1 {
    }
    interface DsInput1 {
        "dsValue"?: any;
        "onDsValueChange"?: (event: CustomEvent<string>) => void;
    }
    interface DsSelect1 {
        "dsValue"?: any;
        "onDsValueChange"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "ds-form-1": DsForm1;
        "ds-input-1": DsInput1;
        "ds-select-1": DsSelect1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-form-1": LocalJSX.DsForm1 & JSXBase.HTMLAttributes<HTMLDsForm1Element>;
            "ds-input-1": LocalJSX.DsInput1 & JSXBase.HTMLAttributes<HTMLDsInput1Element>;
            "ds-select-1": LocalJSX.DsSelect1 & JSXBase.HTMLAttributes<HTMLDsSelect1Element>;
        }
    }
}
