/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsProp {
        /**
          * 参数名称
         */
        "name": string;
        /**
          * 参数类型
         */
        "type": 'string' | 'array' | 'json';
    }
    interface DsScript {
    }
    interface Dsb5FunctionTest {
        /**
          * 需要执行的全局函数
         */
        "fun": string;
        /**
          * 需要执行函数的参数
         */
        "params": any[];
        /**
          * 执行函数的结果
         */
        "result": any[];
        /**
          * 展示用例的类型
         */
        "type": 'testCase';
    }
    interface Dsb5Test {
        /**
          * 一个字符串参数
         */
        "prop": string;
        /**
          * 一个字符串数组参数1
         */
        "propArr": string[];
    }
}
declare global {
    interface HTMLDsPropElement extends Components.DsProp, HTMLStencilElement {
    }
    var HTMLDsPropElement: {
        prototype: HTMLDsPropElement;
        new (): HTMLDsPropElement;
    };
    interface HTMLDsScriptElement extends Components.DsScript, HTMLStencilElement {
    }
    var HTMLDsScriptElement: {
        prototype: HTMLDsScriptElement;
        new (): HTMLDsScriptElement;
    };
    interface HTMLDsb5FunctionTestElement extends Components.Dsb5FunctionTest, HTMLStencilElement {
    }
    var HTMLDsb5FunctionTestElement: {
        prototype: HTMLDsb5FunctionTestElement;
        new (): HTMLDsb5FunctionTestElement;
    };
    interface HTMLDsb5TestElement extends Components.Dsb5Test, HTMLStencilElement {
    }
    var HTMLDsb5TestElement: {
        prototype: HTMLDsb5TestElement;
        new (): HTMLDsb5TestElement;
    };
    interface HTMLElementTagNameMap {
        "ds-prop": HTMLDsPropElement;
        "ds-script": HTMLDsScriptElement;
        "dsb5-function-test": HTMLDsb5FunctionTestElement;
        "dsb5-test": HTMLDsb5TestElement;
    }
}
declare namespace LocalJSX {
    interface DsProp {
        /**
          * 参数名称
         */
        "name": string;
        /**
          * 解析参数后回调事件
         */
        "onGetProp"?: (event: CustomEvent<{ key: string; value: any }>) => void;
        /**
          * 参数类型
         */
        "type"?: 'string' | 'array' | 'json';
    }
    interface DsScript {
    }
    interface Dsb5FunctionTest {
        /**
          * 需要执行的全局函数
         */
        "fun": string;
        /**
          * 需要执行函数的参数
         */
        "params"?: any[];
        /**
          * 执行函数的结果
         */
        "result"?: any[];
        /**
          * 展示用例的类型
         */
        "type"?: 'testCase';
    }
    interface Dsb5Test {
        /**
          * 一个字符串参数
         */
        "prop"?: string;
        /**
          * 一个字符串数组参数1
         */
        "propArr"?: string[];
    }
    interface IntrinsicElements {
        "ds-prop": DsProp;
        "ds-script": DsScript;
        "dsb5-function-test": Dsb5FunctionTest;
        "dsb5-test": Dsb5Test;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-prop": LocalJSX.DsProp & JSXBase.HTMLAttributes<HTMLDsPropElement>;
            "ds-script": LocalJSX.DsScript & JSXBase.HTMLAttributes<HTMLDsScriptElement>;
            "dsb5-function-test": LocalJSX.Dsb5FunctionTest & JSXBase.HTMLAttributes<HTMLDsb5FunctionTestElement>;
            "dsb5-test": LocalJSX.Dsb5Test & JSXBase.HTMLAttributes<HTMLDsb5TestElement>;
        }
    }
}
