/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface H5Div {
    }
    interface H5Span {
    }
}
declare global {
    interface HTMLH5DivElement extends Components.H5Div, HTMLStencilElement {
    }
    var HTMLH5DivElement: {
        prototype: HTMLH5DivElement;
        new (): HTMLH5DivElement;
    };
    interface HTMLH5SpanElement extends Components.H5Span, HTMLStencilElement {
    }
    var HTMLH5SpanElement: {
        prototype: HTMLH5SpanElement;
        new (): HTMLH5SpanElement;
    };
    interface HTMLElementTagNameMap {
        "h5-div": HTMLH5DivElement;
        "h5-span": HTMLH5SpanElement;
    }
}
declare namespace LocalJSX {
    interface H5Div {
    }
    interface H5Span {
    }
    interface IntrinsicElements {
        "h5-div": H5Div;
        "h5-span": H5Span;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "h5-div": LocalJSX.H5Div & JSXBase.HTMLAttributes<HTMLH5DivElement>;
            "h5-span": LocalJSX.H5Span & JSXBase.HTMLAttributes<HTMLH5SpanElement>;
        }
    }
}
