/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Bootstrap4StencliTest {
    }
}
declare global {
    interface HTMLBootstrap4StencliTestElement extends Components.Bootstrap4StencliTest, HTMLStencilElement {
    }
    var HTMLBootstrap4StencliTestElement: {
        prototype: HTMLBootstrap4StencliTestElement;
        new (): HTMLBootstrap4StencliTestElement;
    };
    interface HTMLElementTagNameMap {
        "bootstrap-4-stencli-test": HTMLBootstrap4StencliTestElement;
    }
}
declare namespace LocalJSX {
    interface Bootstrap4StencliTest {
    }
    interface IntrinsicElements {
        "bootstrap-4-stencli-test": Bootstrap4StencliTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bootstrap-4-stencli-test": LocalJSX.Bootstrap4StencliTest & JSXBase.HTMLAttributes<HTMLBootstrap4StencliTestElement>;
        }
    }
}
